-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
local STARTING_ID = 0xBE0C00
LOCATION_MAPPING = {
    [STARTING_ID + 0x000E] = {"@Stages/Agile/Agile"},
    [STARTING_ID + 0x000F] = {"@Stages/Serges/Serges"},
    [STARTING_ID + 0x0010] = {"@Stages/Violen/Violen"},

    [STARTING_ID + 0x0040] = {"@Stages/Intro Stage/HP Pickup 1 (Before spike pit)"},
    [STARTING_ID + 0x0041] = {"@Stages/Intro Stage/HP Pickup 2 (Before boss room)"},
    [STARTING_ID + 0x0000] = {"@Stages/Intro Stage/Gigantic Mechaniloid CF-0"},
    [STARTING_ID + 0x00C8] = {"@Stages/Intro Stage/Stage Clear"},

    [STARTING_ID + 0x001F] = {"@Stages/Bubble Crab/Heart Tank"},
    [STARTING_ID + 0x0026] = {"@Stages/Bubble Crab/Sub Tank"},
    [STARTING_ID + 0x0002] = {"@Stages/Bubble Crab/Bubble Crab"},
    [STARTING_ID + 0x00C1] = {"@Stages/Bubble Crab/Stage Clear"},
    [STARTING_ID + 0x0048] = {"@Stages/Bubble Crab/1-Up Pickup (Below Spin Wheel blocks before water section)"},
    [STARTING_ID + 0x004B] = {"@Stages/Bubble Crab/Weapon Energy Pickup 1 (Top-right ledge in seabed section)"},
    [STARTING_ID + 0x004E] = {"@Stages/Bubble Crab/Weapon Energy Pickup 2 (Artificial cave in seabed section)"},
    [STARTING_ID + 0x0049] = {"@Stages/Bubble Crab/HP Pickup 1 (Ledge before water section)"},
    [STARTING_ID + 0x004A] = {"@Stages/Bubble Crab/HP Pickup 2 (Top-right opening above metal floor)"},
    [STARTING_ID + 0x004C] = {"@Stages/Bubble Crab/HP Pickup 3 (First pit in seabed section)"},
    [STARTING_ID + 0x004D] = {"@Stages/Bubble Crab/HP Pickup 4 (Artificial cave in seabed section)"},
    [STARTING_ID + 0x004F] = {"@Stages/Bubble Crab/HP Pickup 5 (Fake wall below Sub Tank)"},
    [STARTING_ID + 0x0050] = {"@Stages/Bubble Crab/HP Pickup 6 (Before boss)"},

    [STARTING_ID + 0x0023] = {"@Stages/Crystal Snail/Heart Tank"},
    [STARTING_ID + 0x002C] = {"@Stages/Crystal Snail/Helmet Capsule"},
    [STARTING_ID + 0x000B] = {"@Stages/Crystal Snail/Magna Quartz"},
    [STARTING_ID + 0x000A] = {"@Stages/Crystal Snail/Crystal Snail"},
    [STARTING_ID + 0x00C5] = {"@Stages/Crystal Snail/Stage Clear"},
    [STARTING_ID + 0x006D] = {"@Stages/Crystal Snail/1-Up Pickup 1 (Under crystal blocks before Magna Quartz)"},
    [STARTING_ID + 0x006F] = {"@Stages/Crystal Snail/1-Up Pickup 2 (Fake ceiling next to Helmet Capsule)"},
    [STARTING_ID + 0x006B] = {"@Stages/Crystal Snail/Weapon Energy Pickup (Under crystal blocks before X-Hunter room)"},
    [STARTING_ID + 0x006A] = {"@Stages/Crystal Snail/HP Pickup 1 (Under crystal blocks before X-Hunter room)"},
    [STARTING_ID + 0x008D] = {"@Stages/Crystal Snail/HP Pickup 2 (After X-Hunter room)"},
    [STARTING_ID + 0x006C] = {"@Stages/Crystal Snail/HP Pickup 3 (Under crystal blocks before Magna Quartz)"},
    [STARTING_ID + 0x006E] = {"@Stages/Crystal Snail/HP Pickup 4 (In giant crystal slide section)"},

    [STARTING_ID + 0x0051] = {"@Stages/Flame Stag/1-Up Pickup 1 (Top-right of first Beetron section)"},
    [STARTING_ID + 0x0058] = {"@Stages/Flame Stag/1-Up Pickup 2 (Bottom of rising lava section)"},
    [STARTING_ID + 0x005F] = {"@Stages/Flame Stag/1-Up Pickup 3 (Above third pillar in lava cave section)"},
    [STARTING_ID + 0x0003] = {"@Stages/Flame Stag/Flame Stag"},
    [STARTING_ID + 0x00C2] = {"@Stages/Flame Stag/Stage Clear"},
    [STARTING_ID + 0x0053] = {"@Stages/Flame Stag/Weapon Energy Pickup 1 (Cave before first lava section)"},
    [STARTING_ID + 0x0055] = {"@Stages/Flame Stag/Weapon Energy Pickup 2 (Cave before first lava section)"},
    [STARTING_ID + 0x005A] = {"@Stages/Flame Stag/Weapon Energy Pickup 3 (Second ledge in rising lava section)"},
    [STARTING_ID + 0x005D] = {"@Stages/Flame Stag/Weapon Energy Pickup 4 (Bottom-left of lava cave section)"},
    [STARTING_ID + 0x0020] = {"@Stages/Flame Stag/Heart Tank"},
    [STARTING_ID + 0x0052] = {"@Stages/Flame Stag/HP Pickup 1 (Cave before first lava section)"},
    [STARTING_ID + 0x0054] = {"@Stages/Flame Stag/HP Pickup 2 (Cave before first lava section)"},
    [STARTING_ID + 0x0056] = {"@Stages/Flame Stag/HP Pickup 3 (Cave before first lava section)"},
    [STARTING_ID + 0x0057] = {"@Stages/Flame Stag/HP Pickup 4 (First ledge in rising lava section)"},
    [STARTING_ID + 0x0059] = {"@Stages/Flame Stag/HP Pickup 5 (Second ledge in rising lava section)"},
    [STARTING_ID + 0x005B] = {"@Stages/Flame Stag/HP Pickup 6 (After rising lava section)"},
    [STARTING_ID + 0x005C] = {"@Stages/Flame Stag/HP Pickup 7 (Bottom-left of lava cave section)"},
    [STARTING_ID + 0x005E] = {"@Stages/Flame Stag/HP Pickup 8 (Before X-Hunter room)"},
    [STARTING_ID + 0x0060] = {"@Stages/Flame Stag/HP Pickup 9 (Ledge in gas pipes section)"},
    [STARTING_ID + 0x0028] = {"@Stages/Flame Stag/Sub Tank"},

    [STARTING_ID + 0x0007] = {"@Stages/Magna Centipede/Magna Centipede"},
    [STARTING_ID + 0x00C4] = {"@Stages/Magna Centipede/Stage Clear"},
    [STARTING_ID + 0x0022] = {"@Stages/Magna Centipede/Heart Tank"},
    [STARTING_ID + 0x0068] = {"@Stages/Magna Centipede/HP Pickup 1 (After Chop Register)"},
    [STARTING_ID + 0x0069] = {"@Stages/Magna Centipede/HP Pickup 2 (Before X-Hunter room)"},
    [STARTING_ID + 0x0008] = {"@Stages/Magna Centipede/Chop Register"},
    [STARTING_ID + 0x0009] = {"@Stages/Magna Centipede/Raider Killer"},
    [STARTING_ID + 0x0027] = {"@Stages/Magna Centipede/Sub Tank"},

    [STARTING_ID + 0x0063] = {"@Stages/Morph Moth/HP Pickup 1 (Before vertical ladder section)"},
    [STARTING_ID + 0x0064] = {"@Stages/Morph Moth/HP Pickup 2 (Left ledge in vertical ladder section)"},
    [STARTING_ID + 0x0065] = {"@Stages/Morph Moth/HP Pickup 3 (Right ledge in vertical ladder section)"},
    [STARTING_ID + 0x0066] = {"@Stages/Morph Moth/HP Pickup 4 (Bottom of magnet ceiling section)"},
    [STARTING_ID + 0x0067] = {"@Stages/Morph Moth/HP Pickup 5 (Bottom of magnet ceiling section)"},
    [STARTING_ID + 0x0061] = {"@Stages/Morph Moth/1-Up Pickup 1 (Left of Heart Tank)"},
    [STARTING_ID + 0x0062] = {"@Stages/Morph Moth/1-Up Pickup 2 (Top-left ledge before Pararoid S-38 #1)"},
    [STARTING_ID + 0x002B] = {"@Stages/Morph Moth/Body Capsule"},
    [STARTING_ID + 0x0021] = {"@Stages/Morph Moth/Heart Tank"},
    [STARTING_ID + 0x0005] = {"@Stages/Morph Moth/Pararoid S-38 #1"},
    [STARTING_ID + 0x0006] = {"@Stages/Morph Moth/Pararoid S-38 #2"},
    [STARTING_ID + 0x0004] = {"@Stages/Morph Moth/Morph Moth"},
    [STARTING_ID + 0x00C3] = {"@Stages/Morph Moth/Stage Clear"},

    [STARTING_ID + 0x0071] = {"@Stages/Overdrive Ostrich/1-Up Pickup (Top-right ledge in outdoors bike section)"},
    [STARTING_ID + 0x0073] = {"@Stages/Overdrive Ostrich/Weapon Energy Pickup 1 (On spikes before Legs Capsule)"},
    [STARTING_ID + 0x0075] = {"@Stages/Overdrive Ostrich/Weapon Energy Pickup 2 (On spikes before Legs Capsule)"},
    [STARTING_ID + 0x0070] = {"@Stages/Overdrive Ostrich/HP Pickup 1 (Behind Spin Wheel blocks before X-Hunter room)"},
    [STARTING_ID + 0x0072] = {"@Stages/Overdrive Ostrich/HP Pickup 2 (On spikes before Legs Capsule)"},
    [STARTING_ID + 0x0074] = {"@Stages/Overdrive Ostrich/HP Pickup 3 (On spikes before Legs Capsule)"},
    [STARTING_ID + 0x002D] = {"@Stages/Overdrive Ostrich/Legs Capsule"},
    [STARTING_ID + 0x0024] = {"@Stages/Overdrive Ostrich/Heart Tank"},
    [STARTING_ID + 0x000C] = {"@Stages/Overdrive Ostrich/Overdrive Ostrich"},
    [STARTING_ID + 0x00C6] = {"@Stages/Overdrive Ostrich/Stage Clear"},

    [STARTING_ID + 0x0044] = {"@Stages/Wheel Gator/1-Up Pickup (Top of elevator)"},
    [STARTING_ID + 0x0045] = {"@Stages/Wheel Gator/Weapon Energy Pickup (Ledge in left elevator exit)"},
    [STARTING_ID + 0x0042] = {"@Stages/Wheel Gator/HP Pickup 1 (High ledge after spikes section)"},
    [STARTING_ID + 0x0043] = {"@Stages/Wheel Gator/HP Pickup 2 (Ledge before Ride Armor)"},
    [STARTING_ID + 0x0046] = {"@Stages/Wheel Gator/HP Pickup 3 (Hidden behind top column after X-Hunter room)"},
    [STARTING_ID + 0x0047] = {"@Stages/Wheel Gator/HP Pickup 4 (Ledge before boss room)"},
    [STARTING_ID + 0x008A] = {"@Stages/Wheel Gator/HP Pickup 5 (Hidden behind metal slope in exterior section)"},
    [STARTING_ID + 0x008B] = {"@Stages/Wheel Gator/HP Pickup 6 (Hidden behind metal slope in exterior section)"},
    [STARTING_ID + 0x008C] = {"@Stages/Wheel Gator/HP Pickup 7 (Hidden behind metal slope in exterior section)"},
    [STARTING_ID + 0x001E] = {"@Stages/Wheel Gator/Heart Tank"},
    [STARTING_ID + 0x002A] = {"@Stages/Wheel Gator/Arms Capsule"},
    [STARTING_ID + 0x0001] = {"@Stages/Wheel Gator/Wheel Gator"},
    [STARTING_ID + 0x00C0] = {"@Stages/Wheel Gator/Stage Clear"},

    [STARTING_ID + 0x0076] = {"@Stages/Wire Sponge/1-Up Pickup (Above flying platforms in rainy section)"},
    [STARTING_ID + 0x0077] = {"@Stages/Wire Sponge/HP Pickup 1 (Before X-Hunter room)"},
    [STARTING_ID + 0x0078] = {"@Stages/Wire Sponge/HP Pickup 2 (Before boss room)"},
    [STARTING_ID + 0x0029] = {"@Stages/Wire Sponge/Sub Tank"},
    [STARTING_ID + 0x0025] = {"@Stages/Wire Sponge/Heart Tank"},
    [STARTING_ID + 0x000D] = {"@Stages/Wire Sponge/Wire Sponge"},
    [STARTING_ID + 0x00C7] = {"@Stages/Wire Sponge/Stage Clear"},

    [STARTING_ID + 0x0079] = {"@Stages/X Hunter Base Stage 1/1-Up Pickup 1 (Right ledge after start)"},
    [STARTING_ID + 0x007B] = {"@Stages/X Hunter Base Stage 1/1-Up Pickup 2 (Below flying platforms section)"},
    [STARTING_ID + 0x007A] = {"@Stages/X Hunter Base Stage 1/HP Pickup (Below flying platforms section)"},
    [STARTING_ID + 0x0011] = {"@Stages/X Hunter Base Stage 1/Neo Violen"},

    [STARTING_ID + 0x007D] = {"@Stages/X Hunter Base Stage 2/1-Up Pickup (Behind Spin Wheel blocks)"},
    [STARTING_ID + 0x007C] = {"@Stages/X Hunter Base Stage 2/HP Pickup (Behind Spin Wheel blocks)"},
    [STARTING_ID + 0x0012] = {"@Stages/X Hunter Base Stage 2/Serges Tank"},

    [STARTING_ID + 0x007E] = {"@Stages/X Hunter Base Stage 3/HP Pickup 1 (In Strike Chain hole after start)"},
    [STARTING_ID + 0x0080] = {"@Stages/X Hunter Base Stage 3/HP Pickup 2 (Before second moving platform section)"},
    [STARTING_ID + 0x0081] = {"@Stages/X Hunter Base Stage 3/HP Pickup 3 (Before second moving platform section)"},
    [STARTING_ID + 0x0082] = {"@Stages/X Hunter Base Stage 3/HP Pickup 4 (Before second moving platform section)"},
    [STARTING_ID + 0x0083] = {"@Stages/X Hunter Base Stage 3/HP Pickup 5 (Top of second moving platform section)"},
    [STARTING_ID + 0x0084] = {"@Stages/X Hunter Base Stage 3/HP Pickup 6 (Top of second moving platform section)"},
    [STARTING_ID + 0x0086] = {"@Stages/X Hunter Base Stage 3/HP Pickup 7 (Ledge before charged Speed Burner + air dash section)"},
    [STARTING_ID + 0x0087] = {"@Stages/X Hunter Base Stage 3/HP Pickup 8 (Ledge before charged Speed Burner + air dash section)"},
    [STARTING_ID + 0x007F] = {"@Stages/X Hunter Base Stage 3/1-Up Pickup 1 (In Strike Chain hole after start)"},
    [STARTING_ID + 0x0085] = {"@Stages/X Hunter Base Stage 3/1-Up Pickup 2 (Before charged Speed Burner + air dash section)"},
    [STARTING_ID + 0x0088] = {"@Stages/X Hunter Base Stage 3/1-Up Pickup 3 (After charged Speed Burner + air dash section)"},
    [STARTING_ID + 0x0089] = {"@Stages/X Hunter Base Stage 3/1-Up Pickup 4 (On spikes after last vertical section)"},
    [STARTING_ID + 0x002E] = {"@Stages/X Hunter Base Stage 3/Shoryuken Capsule"},
    [STARTING_ID + 0x0013] = {"@Stages/X Hunter Base Stage 3/Agile Flyer"},

    [STARTING_ID + 0x0017] = {"@Stages/X Hunter Base Stage 4/Bubble Crab Rematch"},
    [STARTING_ID + 0x001B] = {"@Stages/X Hunter Base Stage 4/Crystal Snail Rematch"},
    [STARTING_ID + 0x0018] = {"@Stages/X Hunter Base Stage 4/Flame Stag Rematch"},
    [STARTING_ID + 0x001A] = {"@Stages/X Hunter Base Stage 4/Magna Centipede Rematch"},
    [STARTING_ID + 0x0019] = {"@Stages/X Hunter Base Stage 4/Morph Moth Rematch"},
    [STARTING_ID + 0x001C] = {"@Stages/X Hunter Base Stage 4/Overdrive Ostrich Rematch"},
    [STARTING_ID + 0x0016] = {"@Stages/X Hunter Base Stage 4/Wheel Gator Rematch"},
    [STARTING_ID + 0x001D] = {"@Stages/X Hunter Base Stage 4/Wire Sponge Rematch"},
    [STARTING_ID + 0x00C9] = {"@Stages/X Hunter Base Stage 4/Stage Clear"},

    [STARTING_ID + 0x0014] = {"@Stages/X Hunter Base Stage 5/Zero"},
    [STARTING_ID + 0x0015] = {"@Stages/X Hunter Base Stage 5/Sigma"},
}
